### PR TITLE
Disallow to call MqttClient.ConnectAsync while Disconnect is pending.

### LINKED ISSUE #996: Possbile concurrent issue between `ManagedMqttClient.ReconnectIfRequiredAsync()` and `MqttClient.DisconnectInternalAsync()`?
### Describe the bug
Failed to make an reproduce, but I get an MqttClient with `{ IsDisposed=false, _isConnected=true, _backgroundCancellationTokenSource=null,_isDisconnectPending=0, _publishPacketReceiverQueue=null, _keepAlivePacketsSenderTask=canceled, _packetReceiverTask =RanToCompletion, _publishPacketReceiverTask=canceled}` with ManagedMqttClient, and reconnect not work in this state.

Is it possbile concurrent issue between ManagedMqttClient.ReconnectIfRequiredAsync() and `MqttClient.DisconnectInternalAsync()`, if `ReconnectIfRequiredAsync()` is called while `DisconnectInternalAsync()` is still running(IsConnected is already false), and get an MqttClient in conflict state?

### Which project is your bug related to?
- Client : 3.0.12
- ManagedClient : 3.0.12

### To Reproduce
Failed to make an reproduce.

### Expected behavior
Auto reconnected should be handle by ManagedMqttClient after network issue.

### LINKED ISSUE #1010: ManagedClient 3.0.12 will never reconnect,then thread will grow
Line 18048: 2020-10-24 12:48:43.581 +08:00 [INF] mqttNetLog:LogId-,Message-TX (283 bytes) >>> Publish: [Topic= test/gate/up/data] [Payload.Length=259] [QoSLevel=AtMostOnce] [Dup=False] [Retain=False] [PacketIdentifier=],Source-MqttChannelAdapter,Exception:
	Line 18080: 2020-10-24 12:49:14.078 +08:00 [INF] mqttNetLog:LogId-,Message-TX (2 bytes) >>> PingReq,Source-MqttChannelAdapter,Exception:
	Line 18081: 2020-10-24 12:49:14.101 +08:00 [INF] mqttNetLog:LogId-,Message-RX (2 bytes) <<< PingResp,Source-MqttChannelAdapter,Exception:
	Line 18119: 2020-10-24 12:50:07.717 +08:00 [INF] mqttNetLog:LogId-client,Message-Disconnecting [Timeout=00:01:00],Source-MqttClient,Exception:
	Line 18120: 2020-10-24 12:50:07.720 +08:00 [INF] mqttNetLog:LogId-client,Message-Disconnected from adapter.,Source-MqttClient,Exception:
	Line 18157: 2020-10-24 12:50:51.581 +08:00 [INF] mqttNetLog:LogId-client,Message-Trying to connect with server '58.56.66.163:3989' (Timeout=00:01:00).,Source-MqttClient,Exception:
	Line 18159: 2020-10-24 12:50:51.613 +08:00 [INF] mqttNetLog:LogId-client,Message-Connection with server established.,Source-MqttClient,Exception:
	Line 18160: 2020-10-24 12:50:51.613 +08:00 [INF] mqttNetLog:LogId-,Message-TX (76 bytes) >>> Connect: [ClientId=310c37f3-d880-4950-9f59-3b27b832ee9e] [Username=sensorGate1] [Password=****] [KeepAlivePeriod=30] [CleanSession=True],Source-MqttChannelAdapter,Exception:
	Line 18195: 2020-10-24 12:51:35.187 +08:00 [INF] mqttNetLog:LogId-client,Message-Disconnecting [Timeout=00:01:00],Source-MqttClient,Exception:
	Line 18196: 2020-10-24 12:51:35.187 +08:00 [INF] mqttNetLog:LogId-client,Message-Disconnected from adapter.,Source-MqttClient,Exception:

### PR DESCRIPTION
**Pull request by yyjdelete**
Fix #996
Fix #1010

### CODE REVIEW

**Comment by yyjdelete** [comment]
Call MqttClient.ConnectAsync while Disconnect is pending may lead MqttClient to an broken state(disconnect free the resources alloc with the new connection instead of the old one), and block the usage of `ManagedMqttClient`(AutoReconnect may broken the client, and user has no way to check that and restore from the broken state)

An quick testcase can be found at https://github.com/chkr1011/MQTTnet/issues/996#issuecomment-699650850

File: Source/MQTTnet/Client/MqttClient.cs [hunk 1]
```diff
@@ -38,8 +38,11 @@ public class MqttClient : Disposable, IMqttClient
 
         IMqttChannelAdapter _adapter;
         bool _cleanDisconnectInitiated;
-        long _isDisconnectPending;
-        bool _isConnected;
+        volatile int _connectState;
+        const int CONNECT_STATED_DISCONNECTED = 0;
```
Comment (chkr1011) [inline Source/MQTTnet/Client/MqttClient.cs:42]: Please convert this to an enum with PascalCase style because this common in C#. You can also add a private method as a replacement of the _Interlocked.CompareExchange_ calls which will also accept these enums only. Internally the new method will cast the num as integers to that we use the enum only in business code and have the technical conversion and thread safe access stuff separated.

**Review by chkr1011 — CHANGES_REQUESTED** [review]

File: Source/MQTTnet/Server/MqttClientSessionsManager.cs [hunk 2]
```diff
@@ -425,10 +426,13 @@ MqttClientConnection CreateClientConnection(MqttConnectPacket connectPacket, Mqt
                     _connections[connectPacket.ClientId] = connection;
                 }
 
-                existingConnection?.StopAsync(MqttClientDisconnectReason.SessionTakenOver).GetAwaiter().GetResult();
-
-                return connection;
+                if (existingConnection != null)
+                {
+                    await existingConnection.StopAsync(MqttClientDisconnectReason.SessionTakenOver).ConfigureAwait(false);
```
Comment (yyjdelete) [inline Source/MQTTnet/Server/MqttClientSessionsManager.cs:431]: Changes in this file is not required, but `Session_Tests.Manage_Session_MaxParallel()` may failed, because too many threads are blocked by `GetResult()` here when change https://github.com/chkr1011/MQTTnet/blob/7eb6d2d1e3d0480b89cbdafe0dc4380ea5dd055c/Tests/MQTTnet.Core.Tests/Session_Tests.cs#L101 from 10 to 50.

File: Source/MQTTnet/Client/MqttClient.cs [hunk 3]
```diff
@@ -38,8 +38,16 @@ public class MqttClient : Disposable, IMqttClient
 
         IMqttChannelAdapter _adapter;
         bool _cleanDisconnectInitiated;
-        long _isDisconnectPending;
-        bool _isConnected;
+        volatile int _connectState;
+
+        enum ConnectState
```
Comment (chkr1011) [inline Source/MQTTnet/Client/MqttClient.cs:43]: Please move this to a dedicated c# file. In this project we do not have any private classes or enums etc. embedded in other classes. And consider renaming this to "MqttClientConnectionState" which follows the naming pattern in this project.

**Review by chkr1011 — CHANGES_REQUESTED** [review]

File: Source/MQTTnet/Client/MqttClient.cs (hunk 3 above)
Comment (yyjdelete) [reply Source/MQTTnet/Client/MqttClient.cs:43]: I can do this tomorrow, but the name is really easy to be confused with `MQTTnet.Server.MqttClientConnectionStatus`

Comment (chkr1011) [reply Source/MQTTnet/Client/MqttClient.cs:43]: You are right. Maybe we need to use the same name but due to a different namespace it is clear that the scope is a different one?

Comment (yyjdelete) [reply Source/MQTTnet/Client/MqttClient.cs]: Moved to `MQTTnet.Client.MqttClientConnectionStatus` and updated related field/method names.

**Comment by chkr1011** [comment]
Thank you for your contribution. Good work 👍
