### PR TITLE
Remove if clause that stopped handling of tasks with exceptions

### LINKED ISSUE #158: MQTT communication exception while receiving packets
I use the MQTTnet client to connect to aws iot through a presigned url, it works, however, every about 100 seconds (it is pretty accurate every time) it will get disconnected.  i am not sure why.  here is the log i got:

```
>> [2018-01-19T15:59:07.0172770-05:00] [10] [MqttClient] [Verbose]: Trying to connect with server.
>> [2018-01-19T15:59:07.0202781-05:00] [10] [MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:30]
>> [2018-01-19T15:59:07.1783819-05:00] [11] [MqttClient] [Verbose]: Connection with server established.
>> [2018-01-19T15:59:07.1853863-05:00] [7] [MqttClient] [Info]: Start receiving packets.
>> [2018-01-19T15:59:07.3435203-05:00] [5] [MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=360d99a6fe41b3c1c6a095993b7ae9b6d2ca979c9b9cc690de1d03a7fe2f8e51] [Username=] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:30]
>> [2018-01-19T15:59:07.4546491-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=False]
>> [2018-01-19T15:59:07.4696600-05:00] [5] [MqttClient] [Info]: Received <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=False]
>> [2018-01-19T15:59:07.4726629-05:00] [5] [MqttClient] [Verbose]: MQTT connection with server established.
>> [2018-01-19T15:59:07.4886676-05:00] [9] [MqttClient] [Info]: Start sending keep alive packets.
>> [2018-01-19T15:59:07.4896734-05:00] [9] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T15:59:07.4966735-05:00] [5] [MqttChannelAdapter] [Verbose]: TX >>> Subscribe: [PacketIdentifier=1] [TopicFilters=57e581b25854ac000ff6f3ef@AtLeastOnce,59272c7e80e5cf82a30d39fb@AtLeastOnce,57fcd4575730e4000f9ba85f@AtLeastOnce] [Timeout=00:00:30]
>> [2018-01-19T15:59:07.5086791-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T15:59:07.5096801-05:00] [9] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T15:59:07.5527116-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< SubAck: [PacketIdentifier=1] [SubscribeReturnCodes=SuccessMaximumQoS1,SuccessMaximumQoS1,SuccessMaximumQoS1]
>> [2018-01-19T15:59:07.5527116-05:00] [12] [MqttClient] [Info]: Received <<< SubAck: [PacketIdentifier=1] [SubscribeReturnCodes=SuccessMaximumQoS1,SuccessMaximumQoS1,SuccessMaximumQoS1]
>> [2018-01-19T15:59:17.5244169-05:00] [5] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T15:59:17.5444309-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T15:59:17.5454313-05:00] [5] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T15:59:27.5646272-05:00] [5] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T15:59:27.5836342-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T15:59:27.5836342-05:00] [5] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T15:59:37.5868786-05:00] [9] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T15:59:37.6078826-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T15:59:37.6078826-05:00] [12] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T15:59:40.6239881-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< Publish: [Topic=57fcd4575730e4000f9ba85f] [Payload.Length=512] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1]
>> [2018-01-19T15:59:40.6239881-05:00] [9] [MqttClient] [Info]: Received <<< Publish: [Topic=57fcd4575730e4000f9ba85f] [Payload.Length=512] [QoSLevel=AtLeastOnce] [Dup=False] [Retain=False] [PacketIdentifier=1]
>> [2018-01-19T15:59:40.9493656-05:00] [9] [MqttChannelAdapter] [Verbose]: TX >>> PubAck [Timeout=00:00:30]
>> [2018-01-19T15:59:47.6221570-05:00] [9] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T15:59:47.6482058-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T15:59:47.6491995-05:00] [9] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T15:59:57.6662408-05:00] [9] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T15:59:57.6872503-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T15:59:57.6892564-05:00] [9] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T16:00:07.7111522-05:00] [9] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T16:00:07.7321702-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T16:00:07.7331669-05:00] [9] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T16:00:17.7528845-05:00] [12] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T16:00:17.7728972-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T16:00:17.7748992-05:00] [9] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T16:00:27.7791319-05:00] [9] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T16:00:27.8011393-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T16:00:27.8021397-05:00] [9] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T16:00:37.8198474-05:00] [12] [MqttChannelAdapter] [Verbose]: TX >>> PingReq [Timeout=00:00:30]
>> [2018-01-19T16:00:37.8388580-05:00] [7] [MqttChannelAdapter] [Verbose]: RX <<< PingResp
>> [2018-01-19T16:00:37.8388580-05:00] [11] [MqttClient] [Info]: Received <<< PingResp
>> [2018-01-19T16:00:47.4215941-05:00] [7] [MqttClient] [Warning]: MQTT communication exception while receiving packets.
MQTTnet.Exceptions.MqttCommunicationException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.WebSocketStream.<FetchChunkAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.WebSocketStream.<ReadAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.WebSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadByte()
   at MQTTnet.Serializer.MqttPacketReader.ReadHeaderFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<>c__DisplayClass12_0.<<ReceivePacketAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<ReceivePacketsAsync>d__40.MoveNext()
>> [2018-01-19T16:00:47.4676255-05:00] [7] [MqttClient] [Info]: Stopped sending keep alive packets.
>> [2018-01-19T16:00:47.4686240-05:00] [7] [MqttChannelAdapter] [Verbose]: Disconnecting [Timeout=00:00:30]
>> [2018-01-19T16:00:47.4716251-05:00] [7] [MqttClient] [Info]: Disconnected from adapter.
>> [2018-01-19T16:00:47.4716251-05:00] [7] [MqttClient] [Info]: Disconnected.
>> [2018-01-19T16:00:47.4776303-05:00] [7] [MqttClient] [Info]: Stopped receiving packets.

```

I am not sure if this is a issue with aws or not, but just can not find the cause.

### PR DESCRIPTION
**Pull request by jltjohanlindqvist**
If any of the tasks that are awaited with the method `WaitForTaskAsync` throws an exception this would result in an `UnhandledTaskException` and crashing the application. With the changes made here the tasks will always be awaited and thus also the exception will be handled.

Solves the unhandled task exception part of issue #158

### CODE REVIEW

**Comment by JanEggers** [comment]
can you please add a test to prevent regressions?

**Comment by jltjohanlindqvist** [comment]
Sure, I'm at a bit of a loss exactly what you want to test here? Could you give some pointers?

**Comment by JanEggers** [comment]
Ideally a test that shows we have an issue with the if statement and that it is fixed without the if statement

**Comment by jltjohanlindqvist** [comment]
Added a new commit where both the tasks are awaited in a Task.WhenAll to avoid skipping awaiting the second task if an exception is thrown when awaiting the first task.

**Comment by jltjohanlindqvist** [comment]
> Ideally a test that shows we have an issue with the if statement and that it is fixed without the if statement

Yeah, that would be ideal, the problem is that there's a lot of entry points to this place making it really difficult to unit test. I'm open to some pointers where to start though.

**Comment by jltjohanlindqvist** [comment]
Added some more defensive code to avoid unhandled task exceptions.

**Comment by jltjohanlindqvist** [comment]
Seems like the test that failed is a flaky test? Atleast according to this comment:
https://github.com/chkr1011/MQTTnet/blob/efef23e3f55bf600e3322fcd52c5e1b8665403bf/Tests/MQTTnet.Core.Tests/MqttFactory_Tests.cs#L29

File: Source/MQTTnet/Client/MqttClient.cs [hunk 1]
```diff
@@ -626,15 +628,25 @@ private async Task<bool> HandleReceivedApplicationMessageAsync(MqttPublishPacket
...
+                // Return here to avoid deadlocks, but first any eventual exception in the task
+                // must be handled to avoid not getting an unhandled task exception
+                if (!task.IsFaulted)
+                {
+                    return;
+                }
+
+                // By accessing the Exception property the exception is considered handled and will
+                // not result in an unhandled task exception later by the finalizer
+                _logger.Warning(task.Exception, "Exception when waiting for background task.");
```
Comment (chkr1011) [inline Source/MQTTnet/Client/MqttClient.cs]: Usually the errors messages start with "Error while...". Just a very minor thing but it should be aligned in my opinion.

Comment (jltjohanlindqvist) [reply Source/MQTTnet/Client/MqttClient.cs]: I agree.

**Comment by jltjohanlindqvist** [comment]
We're still experiencing the crash this pull request is supposed to fix in our application, but we're still looking into it, so maybe we should hold off a bit until we can exactly pinpoint what is causing our crashes. 

I still believe that the changes in this PR are improvements to the code, but we'll keep investigating and get back with more changes or update you if we find that the issue was in our code.

File: Source/MQTTnet/Client/MqttClient.cs [hunk 2]
```diff
@@ -346,11 +352,24 @@ private Task SendAsync(MqttBasePacket packet, CancellationToken cancellationToke
...
                 }
-                catch (MqttCommunicationTimedOutException)
+                catch (Exception exception)
                 {
-                    _logger.Warning(null, "Timeout while waiting for packet of type '{0}'.", typeof(TResponsePacket).Name);
+                    if (exception is MqttCommunicationTimedOutException)
+                    {
+                        _logger.Warning(null, "Timeout while waiting for packet of type '{0}'.", typeof(TResponsePacket).Name);
+                    }
+
```
Comment (jltjohanlindqvist) [inline Source/MQTTnet/Client/MqttClient.cs]: Make sure that `packetAwaiter.WaitOneAsync(Options.CommunicationTimeout).ConfigureAwait(false);` is always awaited, previously there could be an exception thrown in this call: `await _adapter.SendPacketAsync(requestPacket, Options.CommunicationTimeout, cancellationToken).ConfigureAwait(false);`, which would result in the `packetAwaiter.WaitOneAsync`-method never being called.

**Comment by jltjohanlindqvist** [comment]
My colleague just added some additional logic that has solved all the issues we've seen. We're no longer getting any UnhandledTaskException crashes.

Added some comments in the diff about why the changes were made.
